### PR TITLE
OFFAPPS-336 Avoid erroring out for any interpolation

### PR DESCRIPTION
**Pull request by princemaple**
:koala:

Wrap interpolation in try catch block. Log error.

/cc @zendesk/quokka

### Screenshots
On an existing ticket
dev_-_agent

On a new ticket
dev_-_agent

### Reference
- [JIRA OFFAPPS-336](https://zendesk.atlassian.net/browse/OFFAPPS-336)

### Risks
- N/A

### CODE REVIEW

**Comment by adammw** [comment]
Ha. While I wouldn't really like this approach for anything more complicated, this seems like the easiest way to fix this. :+1:

**Comment by sandlerr** [comment]
console logging fails validation, right? These apps should be examples of best practice IMO

**Comment by princemaple** [comment]
@sandlerr no, console logs do not fail validation. We prefer to not have them, but they are OK to be there for logging errors. Also I used `console.error`

**Comment by sandlerr** [comment]
I'm still not sure about this. What use is that error message to anyone but a developer?

**Comment by princemaple** [comment]
No use, but if a developer wants more information, they can get it from the console.
Do you think we should not log anything at all?

**Comment by sandlerr** [comment]
+1

**Pull request merged**
